#ifndef MYALGORITHM_H
#define MYALGORITHM_H


#include <vtkPolyDataAlgorithm.h>
#include <vtkInformation.h>              // Required for vtkInformation
#include <vtkInformationVector.h>        // Required for vtkInformationVector
#include "MyModuleModule.h"  // Must be generated by CMake!

class MYMODULE_EXPORT MyAlgorithm : public vtkPolyDataAlgorithm {
public:
  static MyAlgorithm* New();
  vtkTypeMacro(MyAlgorithm, vtkPolyDataAlgorithm);

protected:
  MyAlgorithm();
  ~MyAlgorithm() override = default;

  int RequestData(vtkInformation*, vtkInformationVector**, vtkInformationVector*) override;

private:
  MyAlgorithm(const MyAlgorithm&) = delete;
  void operator=(const MyAlgorithm&) = delete;
};

#endif // MYALGORITHM_H
